name: CI

on: [ push ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [Debian-12]
        build_type: [Rel]
        include:
          - name: Debian-12
            image: "debian:bookworm"
    steps:
      - uses: actions/checkout@v4
